### ISSUE TITLE
Question: is BEM required?

### ISSUE THREAD

**Issue by noahehall** [ZeeCoder/container-query#61]
I generally hash my selectors in production and rely on CSS modules. 

How does this repo fit into that environment?

Thanks..

**Comment by ZeeCoder** [comment]
Hi @noahehall !

Issue #18 is exactly about this.

Basically, it wouldn't work out of the box as it is now.

I had some ideas, but since I'm not using css modules I haven't tried any of them. we can continue the discussion there, I'm curious what you might think. 🤔

**Comment by ZeeCoder** [comment]
I've just realised that I haven't addressed your original question: technically you don't need to use any OOCSS methodology, like BEM, but it's not officially supported, so I don't know if it actually would work. 🤔

**Comment by noahehall** [comment]
Thanks @ZeeCoder
