### ISSUE TITLE
Experiment with Houdini

### ISSUE THREAD

**Issue by ZeeCoder** [ZeeCoder/container-query#80]
Paint API will be supported from Chrome 65, might gives us some opportunities:
https://twitter.com/DasSurma/status/954463257552617472

**Comment by ZeeCoder** [comment]
Since this is just about the paint API, it won't really help in this case. :/

**Comment by eeeps** [comment]
The Typed OM (which still fits under the “Houdini” title of this issue) probably will, eventually https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/6ai8np0DSOA

**Comment by eeeps** [comment]
Also – might be worth looking at the [Layout API](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/gVvtbIjE2J4/0KWy4Ew2CQAJ;context-place=forum/blink-dev) and the “layout worklets” referenced [here](https://github.com/w3ctag/design-reviews/issues/187#issuecomment-362633185)? I have no idea what the opportunities provided by theses things are or would be, but it’s been something I've wanted to look into myself.

**Comment by ZeeCoder** [comment]
@eeeps yeah that and the ParserApi seems like would be useful.
But I'll come back to it once a browser gets close enough to implement it. :D

The parser api would allow you to basically come up with custom CSS syntax (@container at-rule, for example) and parse it the way you want.
Then you could execute your JS accordingly.

Quite big actually.
