### ISSUE TITLE
Add information for developers

### ISSUE THREAD

**Issue by ahmadalfy** [ZeeCoder/container-query#91]
It took me a while to discover [Lerna](https://github.com/lerna/lerna) and figure out how to build and run the project. Any hints in the documentation for the developers will definitely be helpful.

Thank you

**Comment by ZeeCoder** [comment]
Yeah I was planning to make a guide once others start contributing.
could you write down a list of some sort that's worth mentioning for first
contributors as you go?

it's hard for me to imagine what could be problematic for new devs. 😅

**Comment by ahmadalfy** [comment]
Sure :) I will be happy to add them to this thread then we figure out the best way to formulate it. Thank you :D

**Comment by ZeeCoder** [comment]
@ahmadalfy I've added a [CONTRIBUTING](https://github.com/ZeeCoder/container-query/blob/master/CONTRIBUTING.md) doc to start with. Feel free to message me if you have any ideas about improvements. :+1:
