### ISSUE TITLE
React 16 warnings

### ISSUE THREAD

**Issue by tjbenneche** [ZeeCoder/container-query#97]
`PropTypes` and `createClass` are being access via the main React library, which will inhibit consumers from using this library with React 16.*

`  console.warn node_modules/react/lib/lowPriorityWarning.js:38
    Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs`

 `console.warn node_modules/react/lib/lowPriorityWarning.js:38
    Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class`

**Comment by ZeeCoder** [comment]
I use this library with React 16, so it should be fine.
I think those warnings are coming from somewhere else. 🤔 

If you look at the code, I don't use createClass at all, and I've installed the prop-types package separately, so I don't import it through the main React package.

**Comment by tjbenneche** [comment]
Ah, you're right - sorry! These errors popped up for me at the same time as I implemented your library, but were related to a separate change. Thanks for the quick reply!

**Comment by ZeeCoder** [comment]
No worries, hope you like it :)
